"""empty message

Revision ID: 888a023070ce
Revises: f2f5805c8c58
Create Date: 2022-04-29 13:01:05.753768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888a023070ce'
down_revision = 'f2f5805c8c58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
